<a href="https://colab.research.google.com/github/KorStats/skku/blob/main/code/1_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%A7%8C%EB%93%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

MessageError: Error: credential propagation was unsuccessful

In [ ]:
import pandas as pd
df=pd.read_csv('/content/gdrive/MyDrive/신문기사_train_original.csv', encoding='utf-8-sig')

In [ ]:
df['길이'] = df['text'].apply(len)

In [ ]:
df=df[df['길이']<1000]
df['category'].value_counts()

category
종합           105204
경제            13362
사회            10185
정치             8470
스포츠            3090
IT,과학           990
교육/입시/NIE       679
보건/의료            39
부동산              38
기업                4
선거                2
북한/한반도정세          2
Name: count, dtype: int64

In [ ]:
import pandas as pd
samples = {'종합': 4000,'경제': 2000,'사회': 2000, '정치' : 2000, '스포츠' : 1000, 'IT,과학' : 500, '교육/입시/NIE' : 500}
sampled_data = pd.DataFrame()
for category, n in samples.items():
    category_data = df[df['category'] == category]
    sampled_category_data = category_data.sample(n=n, random_state=42)
    sampled_data = pd.concat([sampled_data, sampled_category_data], ignore_index=True)
sampled_data.reset_index(drop=True, inplace=True)
sampled_data.head(3)

,id,category,media_type,media_sub_type,publish_date,title,text,abstractive,길이
0,354626680,종합,online,지역지,2019-07-30 16:14:00,"'연 1만 4000건' 전기용품 안전인증 시장, 민간에 실질적 개방","국가기술표준원, '안전인증제품 시험결과 인정계약 체결 지침' 고시 산업통상자원부 국...",산업통상자원부 국가기술표준원은 기관 간 제품시험 결과 인정계약을 체결하는데 필요한 ...,848
1,360807194,종합,online,경제지,2019-09-23 19:01:00,"취준생, 당신은 위메프 MD가 체질",위메프가 2019년 하반기 신입 MD 공개 채용을 진행한다고 23일 밝혔다. 지원서...,"위메프는 특가의 상품의 입점 영업, 상품 기획을 담당하는 2019년 하반기 신입 M...",892
2,368914670,종합,online,전문지,2019-11-28 17:12:39,전국 아파트 2천 가구 대상 실내 라돈 농도 조사,국립환경과학원은 올해 12월부터 4개월 동안 전국 아파트 2천 가구의 실내 라돈 농...,최근 공동주택에서 1급 발암물질인 라돈 문제가 제기되어 국립환경과학원이 올해 12월...,836

In [ ]:
sampled_data['category'].value_counts()

category
종합           4000
경제           2000
사회           2000
정치           2000
스포츠          1000
IT,과학         500
교육/입시/NIE     500
Name: count, dtype: int64

In [ ]:
sampled_data.to_csv('신문기사_단문.csv', encoding='utf-8-sig')

# 법률 장문 데이터

In [ ]:
import pandas as pd
df=pd.read_csv('/content/gdrive/MyDrive/법률_valid_original.csv', encoding='utf-8-sig')

In [ ]:
df['길이'] = df['text'].apply(len)

In [ ]:
df=df[df['길이']>=1000]
df['category'].value_counts()

category
민사      1879
일반행정     823
형사       790
세무       519
특허       188
가사        37
Name: count, dtype: int64

In [ ]:
df.to_csv('법률_장문.csv', encoding='utf-8-sig')